### ISSUE TITLE
导出的视频清晰度不够

### ISSUE THREAD

**Issue by q1998763** [ziyunfei/render-video#2]
![image](https://user-images.githubusercontent.com/14989849/198226166-e0a0c667-0a0b-43ff-bb45-de7c891e33ef.png)
lottie的例子中，感觉生成的视频清晰度有点差，请问应该在哪去调整呢？我试着改了VideoEncoderConfig的bitrate也没用。

**Comment by ziyunfei** [comment]
看起来不差，如果还觉的不够清晰，可以把 canvas 的高度给的更大一点，现在是 50vh，这样导出的 mp4 尺寸就会更大。
