### ISSUE TITLE
DOMException: Failed to execute 'encode' on 'VideoEncoder': Cannot call 'encode' on a closed codec.

### ISSUE THREAD

**Issue by garywill** [ziyunfei/render-video#3]
Hi, 
作者你好，这是个看起来挺有趣的项目。
我在Chromium 117 (Linux) 上尝试了一下你的那几个demo，但都报错
```
Encoder creation error.


index.mjs:89
Uncaught (in promise) DOMException: Failed to execute 'encode' on 'VideoEncoder': Cannot call 'encode' on a closed codec.
    at https://ziyunfei.github.io/render-video/src/index.mjs:89:15
（匿名） @ index.mjs:89
await in （匿名）（异步）
renderVideo @ index.mjs:5
renderButton.onclick @ lottie to mp4.html:28


lottie%20to%20mp4.html:1 
A VideoFrame was garbage collected without being closed. Applications should call close() on frames when done with them to prevent stalls.
```
我不确定是否bug还是我的打开方式不对

**Comment by garywill** [comment]
换了个新点的chrome（这回不用chromium）好了。是不支持chromium的吗？

**Comment by ziyunfei** [comment]
Chromium 没有 mp4 的编码解码器的，因为版权问题。https://twitter.com/ziyunfei/status/1696556146998366454

**Comment by garywill** [comment]
如果要改用开源的vp8的话该怎样改呢？

我在这里看到 https://developer.chrome.com/articles/webcodecs/ 用vp8，自己尝试了chromium上的` codec: "vp8"`是能成功创建VideoEncoder

我尝试将你的代码的`codec: "avc1.420034"`改成了vp8，mp4改webm，但又在后面的ffmpeg部分报错
是不是要重新弄wasmBinaryFile的那串二进制？教下我怎么弄
